#' Generate polygon subbasins and attributed stream lines/points
#'
#' Creates stream vector layers with D8-derived attributes, optionally
#' snapping user-supplied sampling points to the network and splitting
#' reaches at those locations. Then generates subbasin polygons using the D8 pointer and stream rasters,
#' optionally splitting them at sampling points.
#'
#' @details
#' The function also computes optional stream attributes based on the `extra_attr` argument, which can include:
#' - link_slope: Average slope of each stream link.
#' - cont_slope: Continuous slope along the stream network.
#' - USChnLn_To: Total length of upstream channels for each link.
#' - StOrd_Hack, StOrd_Str, StOrd_Hort, StOrd_Shr: Different stream order classifications (Hack, Strahler, Horton, Shreve).
#' These attributes are calculated using WhiteboxTools and added to the final output.
#'
#' This function performs several steps to generate and attribute stream lines and points:
#' 1. It computes stream link attributes using WhiteboxTools based on the D8 flow direction and stream raster layers.
#' 2. It vectorizes the stream links into line features and extracts point-level attributes at each link.
#' 3. If user-supplied sampling points are provided, it snaps them to the nearest stream link (within a specified distance) and splits the stream reaches at those locations, creating new link IDs as needed.
#' 4. It identifies upstream and downstream adjacent links for each point based on the D8 flow direction.
#' Finally, it writes the resulting stream lines, links, and points (with attributes) to a GeoPackage and returns an `ihydro` object containing references to these layers.
#'
#' If "points" are provided, the function will attempt to snap them to the stream network.
#' The `site_id_col` argument specifies the column in the input points that contains unique site IDs.
#' The `snap_distance` argument controls how far a point can be from the stream network to be snapped;
#' if any point cannot be snapped within this distance and `break_on_noSnap` is `TRUE`, an error will be raised.
#' Points snapped to the network will be assigned a new link ID, and the stream reaches will be split at those locations.
#' The artificial split links will have a `link_class` of 6 and a `link_type` of "Sample Point" to distinguish them
#' from the original stream links. Their link IDs will be generated by appending a decimal suffix to the original
#' link ID (e.g., if link 10 is split, the new link might be 10.1; with subsequent splits being 10.2, 10.3, etc.).
#'
#' @param input An `ihydro` object from [process_flowdir()].
#' @param extra_attr Character vector of optional stream attributes.
#' @param points Optional spatial points for sampling locations.
#' @param site_id_col Character. Column name in `points` for site IDs.
#' @param snap_distance Numeric. Max snapping distance in map units.
#' @param break_on_noSnap Logical. Error if any point can't be snapped?
#' @param return_products Logical. Return GIS products?
#' @param temp_dir Character. Temporary file directory.
#' @param compress Logical. Compress rasters?
#' @param verbose Logical.
#'
#' @return An `ihydro` object.
#' The contained vector layers in the output GeoPackage are:
#' - `stream_lines`: Line features representing the stream network, with attributes for each link.
#' - `stream_links`: Point features representing pour-points for subbasins, attributed with `link_id` and extra attributes.
#' - `stream_points`: Point features representing points along stream lines identifying 'nodes' (confluence points), vs 'links' segments joining 'nodes', and also attributed with `link_id`, `trib_id`, upstream and downstream link and trib IDS and a number of extra attributes
#' - `snapped_points`: Point features representing the snapped locations on the stream network Any points beyond snap distance are removed, with a warning if `break_on_noSnap` is `FALSE`.
#' - `original_points`: Point features representing the original sampling locations
#' - `subbasins`: Polygon features representing the subbasins (reach contributing areas) delineated from the D8 flow direction and stream raster, optionally split at sampling points.
#' The function returns an `ihydro` object containing references to these layers, which can be accessed using [read_ihydro()] or listed with [ihydro_layers()].
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage
#' tdir <- tempdir()
#'
#' ex_dem <- ex_data("elev_ned_30m.tif")
#' ex_streams <- ex_data("streams.shp")
#' ex_points <- ex_data("sites_nc.shp")
#' output_gpkg <- file.path(tdir, "output.gpkg")
#'
#' ihydro_obj <- ihydro::process_flowdir(
#'    dem = ex_dem,
#'    threshold = 1000,
#'    burn_streams = ex_streams,
#'    burn_depth = 5,
#'    burn_slope_dist = 250,
#'    burn_slope_depth = 5,
#'    min_length = 3,
#'    depression_corr = "breach",
#'    output_filename = output_gpkg,
#'    return_products = TRUE,
#'    verbose = TRUE
#' )
#'
#' ihydro::generate_vectors(
#'    input = ihydro_obj,
#'    points = ex_points,
#'    site_id_col = "site_id",
#'    snap_distance = 150,
#'    break_on_noSnap = FALSE,
#'    return_products = TRUE,
#'    verbose = TRUE
#' )
#'
#' ihydro::ihydro_layers(ihydro_obj, n = Inf)
#'
#' mapview::mapview(
#'  list(
#'   ihydro::read_ihydro(ihydro_obj, "stream_lines"),
#'   ihydro::read_ihydro(ihydro_obj, "subbasins"),
#'   ihydro::read_ihydro(ihydro_obj, "snapped_points"),
#'  )
#' )
#'
#' }
#'
generate_vectors <- function(
  input,
  extra_attr = c(
    "link_slope",
    "cont_slope",
    "USChnLn_To",
    "Elevation",
    "StOrd_Hack",
    "StOrd_Str",
    "StOrd_Hort",
    "StOrd_Shr"
  ),
  points = NULL,
  site_id_col = NULL,
  snap_distance = NULL,
  break_on_noSnap = TRUE,
  return_products = FALSE,
  temp_dir = NULL,
  compress = FALSE,
  verbose = FALSE
) {
  .check_ihydro(input)
  if (!is.logical(return_products)) {
    cli::cli_abort("{.arg return_products} must be {.code TRUE} or {.code FALSE}.")
  }
  if (!is.logical(verbose)) {
    cli::cli_abort("{.arg verbose} must be {.code TRUE} or {.code FALSE}.")
  }
  if (!is.logical(compress)) {
    cli::cli_abort("{.arg compress} must be {.code TRUE} or {.code FALSE}.")
  }

  if (!is.null(points)) {
    validate_site_id_col(site_id_col)
  }

  temp_dir <- .ensure_temp_dir(temp_dir)
  extra_attr <- match.arg(extra_attr, several.ok = TRUE)

  if (verbose) {
    cli::cli_alert_info("Attributing streamlines")
  }
  hydro_out <- attrib_streamline(
    input = input,
    extra_attr = extra_attr,
    return_products = return_products,
    points = points,
    site_id_col = site_id_col,
    snap_distance = snap_distance,
    break_on_noSnap = break_on_noSnap,
    temp_dir = temp_dir,
    compress = compress,
    verbose = verbose
  )

  if (verbose) {
    cli::cli_alert_info("Generating subbasins")
  }
  hydro_out <- generate_subbasins(
    input = hydro_out,
    points = points,
    return_products = return_products,
    temp_dir = temp_dir,
    verbose = verbose
  )

  structure(hydro_out, class = "ihydro")
}
