#' Generate upstream and downstream flowpath lookup tables
#'
#' Traces upstream and downstream flowpaths from each stream link, storing results
#' in the GeoPackage database tables `ds_flowpaths` and
#' `us_flowpaths`. Optionally computes pairwise distances using [generate_pdist()].
#'
#' @details
#' This function performs a breadth-first traversal of the stream network to identify all flow-connected paths downstream and upstream of each link. It uses the `stream_links_attr` table generated by [generate_vectors()] as input, which contains attributes for each stream link including its immediate upstream and downstream connections. The function iteratively builds the downstream paths starting from exit tributaries (links with no downstream connection) and then traces upstream paths by reversing the downstream paths. Results are stored in the GeoPackage database for efficient querying.
#' If `pwise_dist` is `TRUE`, the function will also compute pairwise flow-connected distances between links using [generate_pdist()], which can be used for weighted analyses. Setting `pwise_all_links` to `TRUE` will compute distances for all pairs of links, regardless of flow connectivity, which can be useful for certain applications but may be computationally intensive for large networks.
#'
#' The function is designed to be efficient and can handle large networks, but the runtime may increase with the size and complexity of the stream network, especially if `pwise_dist` is `TRUE`. It is recommended to run this function on a machine with sufficient resources and to use the `verbose` option to monitor progress.
#'
#' @param input An `ihydro` object from [generate_vectors()].
#' @param temp_dir Temporary file directory.
#' @param pwise_dist Logical. Calculate all downstream flow-connected pairwise distances?
#' @param pwise_all_links Logical. Calculate all flow un-connected pairwise distances?
#' @param return_products Logical. Return GIS products?
#' @param verbose Logical.
#'
#' @return An `ihydro` object.
#' The contained tables in the output GeoPackage are:
#' - `ds_flowpaths`: Downstream flowpaths for each link.
#' - `us_flowpaths`: Upstream flowpaths for each link.
#' - `funcon_pwise_dist`: Pairwise flow-unconnected distances between links (if `pwise_dist = TRUE`).
#' - `fcon_pwise_dist`: Pairwise flow-connected distances between links (if `pwise_dist = TRUE`).
#' - `unnest_catchment`: Unnested catchment areas such that link_ids in each unn_group* do not contain any overlapping subbasin.
#' The function returns an `ihydro` object containing references to the flowpath tables, which can be accessed using [read_ihydro()] or listed with [ihydro_layers()].
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Example usage
#' tdir <- tempdir()
#'
#' ex_dem <- ex_data("elev_ned_30m.tif")
#' ex_streams <- ex_data("streams.shp")
#' ex_points <- ex_data("sites_nc.shp")
#' output_gpkg <- file.path(tdir, "output.gpkg")
#'
#' ihydro_obj <- ihydro::process_flowdir(
#'    dem = ex_dem,
#'    threshold = 1000,
#'    burn_streams = ex_streams,
#'    burn_depth = 5,
#'    burn_slope_dist = 250,
#'    burn_slope_depth = 5,
#'    min_length = 3,
#'    depression_corr = "breach",
#'    output_filename = output_gpkg,
#'    return_products = TRUE,
#'    verbose = TRUE
#' )
#'
#' ihydro::generate_vectors(
#'    input = ihydro_obj,
#'    points = ex_points,
#'    site_id_col = "site_id",
#'    snap_distance = 150,
#'    break_on_noSnap = FALSE,
#'    return_products = TRUE,
#'    verbose = TRUE
#' )
#'
#' ihydro::trace_flowpaths(
#'   input = ihydro_obj,
#'   pwise_dist = TRUE,
#'   pwise_all_links = TRUE,
#'   return_products = TRUE,
#'   verbose = TRUE
#' )
#'
#' ihydro::ihydro_layers(ihydro_obj, n = Inf)
#'
#' # get all upstream link_ids from link_id 800
#' us_800 <- filter(ihydro::read_ihydro(ihydro_obj, "us_flowpaths"), pour_point_id == "800")
#'
#' # get all downstream link_ids from link_id 800
#' ds_800 <- filter(ihydro::read_ihydro(ihydro_obj, "ds_flowpaths"), pour_point_id == "800")
#'
#' lines_out <- ihydro::read_ihydro(ihydro_obj, "stream_lines") |>
#'  dplyr::filter(
#'   link_id %in% us_800$origin_link_id |
#'   link_id %in% ds_800$destination_link_id
#'  )
#'
#' mapview::mapview(lines_out)
#'
#' }
#'
trace_flowpaths <- function(
  input,
  temp_dir = NULL,
  pwise_dist = FALSE,
  pwise_all_links = FALSE,
  return_products = FALSE,
  verbose = FALSE
) {
  check_ihydro(input)
  stopifnot(
    is.logical(verbose),
    is.logical(pwise_dist),
    is.logical(pwise_all_links)
  )

  temp_dir <- ensure_temp_dir(temp_dir)
  db_fp <- input$outfile

  site_id_col <- read_site_id_col(db_fp)

  final_links <- read_ihydro(input, "stream_links_attr") |>
    dplyr::mutate(
      dplyr::across(
        c(link_id, tidyselect::any_of(site_id_col)),
        as.character
      ),
      dplyr::across(
        tidyselect::any_of(site_id_col),
        ~ dplyr::na_if(., "")
      )
    )

  trace_flowpath_fn(
    input = final_links,
    verbose = verbose,
    db_loc = db_fp,
    site_id_col = site_id_col,
    temp_dir = temp_dir
  )

  if (pwise_dist) {
    input <- generate_pdist(
      input = input,
      verbose = verbose,
      return_products = return_products,
      pwise_all_links = pwise_all_links
    )
  }

  if (verbose) {
    message("Calculating unnested catchments")
  }
  unnest_catchments(input)

  clean_temp_files(temp_dir)

  if (return_products) {
    input$us_flowpaths <- read_ihydro(input, "us_flowpaths")
    input$ds_flowpaths <- read_ihydro(input, "ds_flowpaths")
    input$unnest_catchments <- read_ihydro(input, "unnest_catchment")
  }

  structure(input, class = "ihydro")
}


#' @keywords internal
#' @noRd
trace_flowpath_fn <- function(
  input,
  db_loc,
  site_id_col,
  verbose = FALSE,
  temp_dir = NULL
) {
  con <- DBI::dbConnect(RSQLite::SQLite(), db_loc)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  DBI::dbExecute(con, "DROP TABLE IF EXISTS ds_flowpaths")

  # Prepare tributary-level input table
  input_tib <- input |>
    tibble::as_tibble() |>
    dplyr::select(
      link_id,
      trib_id,
      link_lngth,
      sbbsn_area,
      USChnLn_Fr,
      tidyselect::starts_with("uslink_id"),
      tidyselect::starts_with("dslink_id"),
      tidyselect::starts_with("dstrib_id"),
      tidyselect::starts_with("ustrib_id")
    ) |>
    dplyr::filter(!is.na(link_id)) |>
    dplyr::mutate(link_id = as.character(link_id)) |>
    tidyr::pivot_longer(
      cols = c(
        tidyselect::starts_with("uslink_id"),
        tidyselect::starts_with("ustrib_id")
      )
    ) |>
    dplyr::filter(
      dplyr::case_when(
        name %in% c("uslink_id1", "ustrib_id1") ~ TRUE,
        is.na(value) ~ FALSE,
        TRUE ~ TRUE
      )
    ) |>
    dplyr::mutate(
      name = ifelse(grepl("trib", name), "ustrib_id1", "uslink_id1")
    ) |>
    tidyr::pivot_wider(
      names_from = name,
      values_from = value,
      values_fn = list
    ) |>
    tidyr::unnest(cols = c(uslink_id1, ustrib_id1)) |>
    dplyr::select(-uslink_id1, -ustrib_id1) |>
    dplyr::distinct() |>
    dplyr::arrange(trib_id, USChnLn_Fr)

  # ── Downstream paths ────────────────────────────────────────────────────
  if (verbose) {
    message("Calculating downstream flowpaths")
  }

  progressr::with_progress(enable = verbose, {
    int_tribs <- input_tib |>
      dplyr::mutate(trib_id2 = trib_id) |>
      dplyr::group_by(trib_id) |>
      tidyr::nest() |>
      dplyr::ungroup() |>
      dplyr::mutate(
        join_id = furrr::future_map(
          data,
          .options = furrr::furrr_options(
            globals = FALSE,
            seed = NULL,
            scheduling = 1L
          ),
          carrier::crate(function(x) {
            `%>%` <- magrittr::`%>%`
            dplyr::arrange(x, USChnLn_Fr) %>%
              utils::tail(1) %>%
              dplyr::select(dslink_id = dslink_id1, dstrib_id = dstrib_id1)
          })
        )
      ) |>
      tidyr::unnest(join_id) |>
      dplyr::mutate(
        join_USChnLn_Fr = input_tib$USChnLn_Fr[
          match(dslink_id, input_tib$link_id)
        ]
      )

    p <- progressr::progressor(steps = nrow(int_tribs))

    # Process exit tributaries (no downstream link)
    exit_tribs <- int_tribs |>
      dplyr::filter(is.na(dslink_id)) |>
      dplyr::select(trib_id, data) |>
      dplyr::mutate(p = list(p)) |>
      dplyr::mutate(
        data2 = furrr::future_map2(
          data,
          p,
          .options = furrr::furrr_options(
            globals = FALSE,
            seed = NULL,
            scheduling = 1L
          ),
          carrier::crate(function(x, p) {
            `%>%` <- magrittr::`%>%`
            x <- x %>%
              dplyr::select(
                link_id,
                trib_id = trib_id2,
                link_lngth,
                sbbsn_area,
                USChnLn_Fr
              )
            ids <- stats::setNames(x$link_id, x$link_id)
            out <- purrr::map(ids, function(y) {
              x[which(x$link_id == y):nrow(x), ] %>%
                dplyr::mutate(origin_id = y)
            }) %>%
              dplyr::bind_rows()
            p()
            out
          })
        )
      )

    exit_ds <- exit_tribs |>
      dplyr::select(data2) |>
      tidyr::unnest(data2)

    dplyr::copy_to(
      con,
      exit_ds |>
        dplyr::select(
          destination_link_id = link_id,
          origin_link_id = origin_id
        ),
      "ds_flowpaths",
      overwrite = TRUE,
      temporary = FALSE,
      indexes = c("destination_link_id", "origin_link_id"),
      analyze = TRUE,
      in_transaction = TRUE
    )

    completed_tribs <- unique(exit_ds$trib_id)
    int_tribs <- dplyr::filter(int_tribs, !trib_id %in% completed_tribs)

    # Helper to look up existing downstream paths
    ds_lookup <- function(dslink_ids) {
      DBI::dbGetQuery(
        con,
        paste0(
          "SELECT * FROM ds_flowpaths WHERE origin_link_id IN (",
          paste0(dslink_ids, collapse = ","),
          ")"
        )
      ) |>
        dplyr::group_by(origin_link_id) |>
        tidyr::nest() |>
        dplyr::ungroup()
    }

    # Iteratively process remaining tributaries
    while (nrow(int_tribs) > 0) {
      batch <- int_tribs |>
        dplyr::filter(dstrib_id %in% completed_tribs) |>
        dplyr::mutate(p = list(p))

      ds_paths_raw <- ds_lookup(batch$dslink_id)
      ds_paths <- ds_paths_raw$data
      names(ds_paths) <- ds_paths_raw$origin_link_id
      batch$ds_path <- ds_paths[as.character(batch$dslink_id)]

      batch <- batch |>
        dplyr::mutate(
          ds_path = furrr::future_pmap(
            list(data = data, ds_path = ds_path, p = p),
            .options = furrr::furrr_options(
              globals = FALSE,
              seed = NULL,
              scheduling = 1L
            ),
            carrier::crate(function(data, ds_path, p) {
              `%>%` <- magrittr::`%>%`
              out <- dplyr::bind_rows(
                data %>%
                  dplyr::select(link_id) %>%
                  dplyr::rename(destination_link_id = link_id),
                ds_path
              ) %>%
                dplyr::distinct()
              ids <- stats::setNames(data$link_id, data$link_id)
              out_list <- purrr::map2(
                ids,
                rep(list(out), length(ids)),
                function(y, x) {
                  dplyr::mutate(
                    x[which(x$destination_link_id == y):nrow(x), ],
                    origin_link_id = y
                  )
                }
              )
              p()
              dplyr::bind_rows(out_list)
            })
          )
        )

      new_rows <- batch |>
        dplyr::select(ds_path) |>
        tidyr::unnest(ds_path)

      DBI::dbAppendTable(con, "ds_flowpaths", new_rows)

      completed_tribs <- dplyr::tbl(con, "ds_flowpaths") |>
        dplyr::left_join(
          dplyr::tbl(con, "stream_links_attr") |>
            dplyr::select(link_id, trib_id),
          by = c("destination_link_id" = "link_id")
        ) |>
        dplyr::select(trib_id) |>
        dplyr::distinct() |>
        dplyr::collect() |>
        dplyr::pull(trib_id)

      int_tribs <- dplyr::filter(int_tribs, !trib_id %in% completed_tribs)
    }
  })

  # ── Upstream paths (reverse of downstream) ──────────────────────────────
  if (verbose) {
    message("Calculating upstream flowpaths")
  }
  DBI::dbExecute(con, "DROP TABLE IF EXISTS us_flowpaths")

  dplyr::tbl(con, "ds_flowpaths") |>
    dplyr::select(pour_point_id = origin_link_id) |>
    dplyr::distinct() |>
    dplyr::full_join(
      dplyr::tbl(con, "ds_flowpaths"),
      by = c("pour_point_id" = "destination_link_id")
    ) |>
    dplyr::copy_to(
      con,
      df = _,
      "us_flowpaths",
      overwrite = TRUE,
      temporary = FALSE,
      indexes = c("pour_point_id", "origin_link_id"),
      analyze = TRUE,
      in_transaction = TRUE
    )

  invisible(db_loc)
}

#' Generate a short random ID
#' @noRd
rand_id <- function(n = 1, d = 12) {
  paste0(replicate(d, sample(c(LETTERS, letters, 0:9), n, TRUE)), collapse = "")
}

#' @keywords internal
#' @noRd
unnest_catchments <- function(input) {
  fp <- read_ihydro(input, "us_flowpaths")
  fp$connected <- 1

  fp <- tidyr::pivot_wider(
    fp,
    id_cols = "pour_point_id",
    names_from = "origin_link_id",
    values_from = "connected",
    values_fill = 0
  )

  fp_mat <- as.matrix(fp[, -1])
  rownames(fp_mat) <- fp$pour_point_id

  overlap_matrix <- Matrix::tcrossprod(fp_mat)

  # adjacency: 1 = overlap, 0 = no overlap
  adj <- overlap_matrix > 0
  diag(adj) <- FALSE

  g <- igraph::graph_from_adjacency_matrix(adj, mode = "undirected")
  groups <- igraph::greedy_vertex_coloring(g)
  group_meta <- data.frame(
    link_id = names(groups),
    unn_group = groups
  ) |>
    dplyr::group_by(unn_group) |>
    dplyr::mutate(
      unn_group = rand_id(1),
      unn_group_size = dplyr::n()
    ) |>
    dplyr::ungroup()

  sf::write_sf(
    group_meta,
    input$outfile,
    layer = "unnest_catchment",
    append = TRUE,
    delete_layer = FALSE,
    delete_dsn = FALSE
  )

  invisible(group_meta)
}
